#it inherits configuration from application.yml
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tool_share_management_platform
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #when start application it runs - development environment
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOSTNAME} # smtp.gmail.com
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enabled: true
        protocol: smtp

#own information/properties
application:
  file:
    upload:
      pictures-output-path: ./tool-sharing-ui/src #directory in the root folder (angular project)
  security:
    jwt:
      secret-key: 9741f747c3dc3985f70c26446f371db4f2766663fa19d045bbecb1456494f6a0
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://localhost:4200, http://localhost:6655
