#it inherits configuration from application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tool_share_management_platform
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #when start application it runs - development environment
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: felix
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

#own information/properties
application:
  file:
    upload:
      pictures-output-path: ./uploads #directory in the root folder
  security:
    jwt:
      secret-key: 9741f747c3dc3985f70c26446f371db4f2766663fa19d045bbecb1456494f6a0
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
