services:
  postgres:
    container_name: postgres-sql-tsmp
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: tool_share_management_platform
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - tool-share-platform
    restart: unless-stopped

  tsmp-api:
    container_name: tsmp-api
    image: tsmp/tsmp:1.0.1  # Specify the local image with the tag you used
    ports:
      - 8080:8080
    networks:
      - tool-share-platform
    depends_on:
      - postgres

  tsmp-ui:
    container_name: tsmp-ui
    image: tsmp/tsmp-ui:1.0.0  # Specify the local image with the tag you used
    ports:
      - 6655:80
    networks:
      - tool-share-platform
    depends_on:
      - tsmp-api

  mail-dev:
    container_name: mail-dev-tsmp
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - tool-share-platform

networks:
  tool-share-platform:
    driver: bridge

volumes:
  postgres:
    driver: local


