/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedToolResponse {
  id?: number;
  name?: string;
  description?: string;
  condition?: string;
  category?: string;
  returnApproved?: boolean;
  returned?: boolean;
  rate?: number;
}
