/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedToolResponse } from '../models/borrowed-tool-response';
export interface PageResponseBorrowedToolResponse {
  content?: Array<BorrowedToolResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
