/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ToolRequest {
  id?: number;
  name: string;
  description: string;
  condition: string;
  category: string;
  available?: boolean;
}
