/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ToolResponse {
  id?: number;
  name?: string;
  description?: string;
  condition?: string;
  category?: string;
  available?: boolean;
  archived?: boolean;
  owner?: string;
  picture?: Array<string>;
  rate?: number;
}
