/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ToolResponse } from '../../models/tool-response';

export interface FindToolById$Params {
  'tool-id': number;
}

export function findToolById(http: HttpClient, rootUrl: string, params: FindToolById$Params, context?: HttpContext): Observable<StrictHttpResponse<ToolResponse>> {
  const rb = new RequestBuilder(rootUrl, findToolById.PATH, 'get');
  if (params) {
    rb.path('tool-id', params['tool-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ToolResponse>;
    })
  );
}

findToolById.PATH = '/tools/{tool-id}';
