name: TSMP_Frontend_UI_Pipeline

on:
  push:
    branches:
      - ci/pipeline
      - prod
    paths:
      - tool-sharing-ui/**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build UI Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract project version
        id: extract_version
        run: |
          cd tool-sharing-ui
          sudo apt-get update && sudo apt-get install -y jq
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: tool-sharing-ui
          file: docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tsmp-ui:${{ steps.extract_version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tsmp-ui:latest
