name: TSMP_Freontend_UI_Pipeline

on:
  push:
    branches:
      - ci/pipeline
      - prod
    paths:
      - tool-sharing-ui/**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml


jobs:
  build-image:
    runs-on: ubuntu
    name: Build UI Docker image
    steps:
      - name: Checkout_code # root-level
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          cd tool-sharing-ui
          apt-get install jq
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v5 #building the image
        with:
          context: tool-sharing-ui #like the context in the Dockerfile
          file: docker/frontend/Dockerfile
          push: true #push to DockerHub
          platforms: linux/amd64 #runs-on ubuntu
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsmp-ui:${{ secrets.DOCKER_TOKEN }}/tsmp-ui:latest

    #  DEPLOYMENT TO CLOUD PLATFORM, REMOTE SERVER (VPS)
    #  deploy: